apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: kaushik0656m21/sampleapp:v3
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: sampleapp-svc
spec:
  type: NodePort
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30003
